### ISSUE TITLE
`client` module is private

### ISSUE THREAD

**Issue by jordonsc** [Stankec/witty#1]
I'm new to Rust so apologies if I'm a retard and this is just me.

Because the `client` module is private, it is impossible to define a `Client` instance _without_ type inference, ie:

    let foo: witty::client::Client = witty::client(...);

This is fine under normal circumstances as you can omit the type and let the compiler work it's magic, unless you're working in a data-structure -

    struct foo {
        bar: witty::client::Client,
    }

Therefore, to store a `Client` in a data-structure either the module `client` needs to be public or a `pub use client::Client;` line needs to be added at the lib level.

Again - if this is just my inexperience, my apologies.

**Comment by monorkin** [comment]
Oh, my. Somehow I completely missed this PR. Yes, you are completely right.

**Comment by monorkin** [comment]
@jordonsc  thank you for the contribution, and please feel free to ping people if they don't respond in one-two days or 6 months :)

> I'm new to Rust so apologies if I'm a retard and this is just me.

Don't degrade your self.

**Comment by monorkin** [comment]
@jordonsc  just to let you know. You contribution became part of the `1.0.0` release today 🎉
Again, thank you for pointing out the issue and making a PR.

**Comment by jordonsc** [comment]
Thanks mate, all good there - glad to see the 1.0.0 release!
